version: '3.8'

services:
  email:
    build: ./email
    container_name: bye-email
    ports:
      - "25:25"
    networks:
      - bye_net

  webmail:
    build: ./webmail
    container_name: bye-webmail
    ports:
      - "8080:80"
    networks:
      - bye_net
    depends_on:
      - email

  dns:
    build: ./dns
    container_name: bye-dns
    #ports:
      #- "53:53/udp"
      #- "53:53/tcp"
    networks:
      - bye_net

  portal:
    build: ./portal
    container_name: bye-portal
    ports:
      - "8081:80"
    networks:
      - bye_net

  proxy_isp:
    build: ./proxy_ISP
    container_name: bye-proxy
    ports:
      - "3128:3128"
    networks:
      - bye_net

networks:
  bye_net:
    driver: bridge
