services:
  # ========================
  # ISP - Infraestrutura
  # ========================

  dns:
    build:
      context: ./dns
      dockerfile: Dockerfile
    container_name: dns
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    networks:
      - rede_isp

  portal_isp:
    build:
      context: ./portal
      dockerfile: Dockerfile
    container_name: portal_isp
    networks:
      - rede_isp

  proxy_isp:
    build:
      context: ./proxy_ISP
      dockerfile: Dockerfile
    container_name: proxy_isp
    ports:
      - "80:80/tcp"
      - "443:443/tcp"
    networks:
      - rede_isp
      - rede_cliente1
networks:
  rede_isp:
    driver: bridge
  rede_cliente1:
    internal: true